---
all:
  vars:
    ansible_python_interpreter: python3
  children:
    devices:
      children:
        ios_router:
          hosts:
            R1:
            R2:
        iosxr_router:
          hosts:
            xrv1:
        asa_firewall:
          hosts:
            asav1:
        nxos_leaf:
          hosts:
            n3k1:
        aireos_wlc:
          hosts:
            vwlc1:
...
